# Canonical Protestant 66-book ordering + Hindi display names.
# Keyed by the English folder name used in the source repo (e.g. "Matthew").
# Only books that actually exist on disk are compiled; the rest sit here so
# the pipeline "just works" as volunteers add folders — no code change needed.

CANON = [
    # (english_folder, hindi_name, testament)
    ("Genesis", "उत्पत्ति", "OT"),
    ("Exodus", "निर्गमन", "OT"),
    ("Leviticus", "लैव्यव्यवस्था", "OT"),
    ("Numbers", "गिनती", "OT"),
    ("Deuteronomy", "व्यवस्थाविवरण", "OT"),
    ("Joshua", "यहोशू", "OT"),
    ("Judges", "न्यायियों", "OT"),
    ("Ruth", "रूत", "OT"),
    ("1 Samuel", "1 शमूएल", "OT"),
    ("2 Samuel", "2 शमूएल", "OT"),
    ("1 Kings", "1 राजा", "OT"),
    ("2 Kings", "2 राजा", "OT"),
    ("1 Chronicles", "1 इतिहास", "OT"),
    ("2 Chronicles", "2 इतिहास", "OT"),
    ("Ezra", "एज्रा", "OT"),
    ("Nehemiah", "नहेम्याह", "OT"),
    ("Esther", "एस्तेर", "OT"),
    ("Job", "अय्यूब", "OT"),
    ("Psalms", "भजन संहिता", "OT"),
    ("Proverbs", "नीतिवचन", "OT"),
    ("Ecclesiastes", "सभोपदेशक", "OT"),
    ("Song of Solomon", "श्रेष्ठगीत", "OT"),
    ("Isaiah", "यशायाह", "OT"),
    ("Jeremiah", "यिर्मयाह", "OT"),
    ("Lamentations", "विलापगीत", "OT"),
    ("Ezekiel", "यहेजकेल", "OT"),
    ("Daniel", "दानिय्येल", "OT"),
    ("Hosea", "होशे", "OT"),
    ("Joel", "योएल", "OT"),
    ("Amos", "आमोस", "OT"),
    ("Obadiah", "ओबद्याह", "OT"),
    ("Jonah", "योना", "OT"),
    ("Micah", "मीका", "OT"),
    ("Nahum", "नहूम", "OT"),
    ("Habakkuk", "हबक्कूक", "OT"),
    ("Zephaniah", "सपन्याह", "OT"),
    ("Haggai", "हाग्गै", "OT"),
    ("Zechariah", "जकर्याह", "OT"),
    ("Malachi", "मलाकी", "OT"),
    ("Matthew", "मत्ती", "NT"),
    ("Mark", "मरकुस", "NT"),
    ("Luke", "लूका", "NT"),
    ("John", "यूहन्ना", "NT"),
    ("Acts", "प्रेरितों के काम", "NT"),
    ("Romans", "रोमियों", "NT"),
    ("1 Corinthians", "1 कुरिन्थियों", "NT"),
    ("2 Corinthians", "2 कुरिन्थियों", "NT"),
    ("Galatians", "गलातियों", "NT"),
    ("Ephesians", "इफिसियों", "NT"),
    ("Philippians", "फिलिप्पियों", "NT"),
    ("Colossians", "कुलुस्सियों", "NT"),
    ("1 Thessalonians", "1 थिस्सलुनीकियों", "NT"),
    ("2 Thessalonians", "2 थिस्सलुनीकियों", "NT"),
    ("1 Timothy", "1 तीमुथियुस", "NT"),
    ("2 Timothy", "2 तीमुथियुस", "NT"),
    ("Titus", "तीतुस", "NT"),
    ("Philemon", "फिलेमोन", "NT"),
    ("Hebrews", "इब्रानियों", "NT"),
    ("James", "याकूब", "NT"),
    ("1 Peter", "1 पतरस", "NT"),
    ("2 Peter", "2 पतरस", "NT"),
    ("1 John", "1 यूहन्ना", "NT"),
    ("2 John", "2 यूहन्ना", "NT"),
    ("3 John", "3 यूहन्ना", "NT"),
    ("Jude", "यहूदा", "NT"),
    ("Revelation", "प्रकाशितवाक्य", "NT"),
]

ORDER = {name: i for i, (name, _hi, _t) in enumerate(CANON)}
HINDI = {name: hi for (name, hi, _t) in CANON}
